context:
  name: font-ttf-rubik
  version: 2.300
  # to update, use check the latest commit touching this directory
  # https://github.com/google/fonts/tree/main/ofl/rubik
  ref: 66f91f10f8e8590367c541bcb5adbe66c933f15f

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/google/fonts/raw/${{ ref }}/ofl/rubik/Rubik%5Bwght%5D.ttf
    sha256: 1b3a7437ba2af80e465e773ed60c5036d1ba6ace492d89046dbcf18fb31e4e88
    file_name: Rubik[wght].ttf
  - url: https://github.com/google/fonts/raw/${{ ref }}/ofl/rubik/Rubik-Italic%5Bwght%5D.ttf
    sha256: 08c6c4018a5ada8b517407b46897e46cf6ebb106853fbd3e89addb51d3b59c62
    file_name: Rubik-Italic[wght].ttf
  - url: https://raw.githubusercontent.com/google/fonts/${{ ref }}/ofl/rubik/OFL.txt
    sha256: 472cbe7c25441df63e9c7864b43eb3c0f4b3df950c66a76224e6cfe1eae843fb

build:
  number: 0
  noarch: generic
  script:
    - mkdir -p $PREFIX/fonts
    - install -v -m644 *.ttf $PREFIX/fonts/

requirements:
  build:
    - __unix

tests:
  - package_contents:
      files:
        - fonts/Rubik-Italic\[wght\].ttf
        - fonts/Rubik\[wght\].ttf

about:
  homepage: https://fonts.google.com/specimen/Rubik
  repository: https://github.com/google/fonts/tree/main/ofl/rubik
  summary: Rubik fonts
  description: |
    Rubik is a sans serif font family with slightly rounded corners designed by Philipp Hubert and Sebastian Fischer at Hubert & Fischer as part of the Chrome Cube Lab project.
  license: OFL-1.1
  license_file: OFL.txt

extra:
  recipe-maintainers:
    - freundTech
    - pavelzw
